# Numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆) `hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆) `hint: vector is a single raw array`

In [3]:
Array_1=np.array([1,2,3,4,5])
print(Array_1)

[1 2 3 4 5]


#### 3. How to find the memory size of any array, creat a random 5x6 array and check the sizs (★☆☆)

In [5]:
random_array=np.random.random((5,6))
print(random_array)
print(random_array.size)
print(random_array.itemsize)

[[0.0253467  0.69329995 0.78105598 0.9110422  0.73105401 0.68479856]
 [0.03806101 0.24162769 0.42257036 0.49659804 0.15275687 0.32331524]
 [0.04841297 0.34955145 0.66976758 0.93347017 0.67730223 0.47331187]
 [0.68202695 0.63070631 0.61703366 0.06149312 0.98117585 0.68891926]
 [0.41732283 0.61936442 0.82269268 0.56145707 0.22192724 0.7594469 ]]
30
8


#### 4. How to get the documentation of the numpy add function from the command line? (★☆☆) `hint: use info or ?`

In [10]:
numpy.add?
import numpy; numpy.info(numpy.add)

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆) `hint: array[x]`

In [16]:
DST= np.zeros(10, dtype=int)
DST[4] = 1
print(DST)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector (single raw array) with values ranging from 10 to 49 (★☆☆) `hint: arange`

In [18]:
Single_Raw_Array=np.arange(10,50)
print(Single_Raw_Array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Show how you can Reverse a vector (first element becomes last) (★☆☆)`hint: use index of -1`

In [19]:
Single_Raw_Array=np.arange(10,50)
Single_Raw_Array = Single_Raw_Array[::-1]
print(Single_Raw_Array)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) `hint: use range and reshape!`

In [20]:
My_Array= np.arange(9).reshape(3, 3)
print(My_Array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) `hint: use the np.nonzero`

In [21]:
Non_Zeors = np.nonzero([1,2,0,0,4,0])
print(Non_Zeors)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) `hint: use index and use np.eye`
the following is an example of 5x4 identity matrix


```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

```



In [24]:
np.eye?
NP_EYE = np.eye(3, dtype=int)
print(NP_EYE)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆) `hint: np.random.random`

In [26]:
Random_Array=np.random.random((3,3,3))
print(Random_Array)

[[[0.02719105 0.3737677  0.07577058]
  [0.6232664  0.74062227 0.91526077]
  [0.97221242 0.35541746 0.90730925]]

 [[0.83606264 0.86146991 0.59778964]
  [0.6085203  0.58907964 0.9406247 ]
  [0.41256989 0.11483789 0.79613822]]

 [[0.34670148 0.09870509 0.68023458]
  [0.67516808 0.61266637 0.67979734]
  [0.97869148 0.75502878 0.82104553]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) `hint: min, max`

In [29]:
Random_Array_1=np.random.random((10,10))
print(Random_Array_1)
print(Random_Array_1.min())
print(Random_Array_1.max())

[[0.22927501 0.82345527 0.30667407 0.21459075 0.39609379 0.27413036
  0.4554611  0.0132449  0.84055916 0.84347729]
 [0.39224978 0.09657822 0.72431556 0.47396392 0.83397077 0.87661109
  0.01761825 0.29399295 0.61460394 0.66889833]
 [0.57071738 0.479543   0.27648449 0.40812179 0.63775164 0.10242439
  0.99169161 0.76990289 0.94328209 0.34483662]
 [0.23195581 0.19808294 0.15085383 0.32633726 0.95108635 0.75813668
  0.29431378 0.57784013 0.41027123 0.39344084]
 [0.55257855 0.35701593 0.7411895  0.46227344 0.78813731 0.73301192
  0.90076471 0.09118284 0.15626309 0.90553143]
 [0.31704266 0.98392027 0.92237459 0.67067683 0.16708694 0.29722453
  0.6610317  0.98561853 0.7607843  0.72925467]
 [0.75578858 0.03084143 0.27303701 0.28360364 0.98126571 0.88762767
  0.64473256 0.85801549 0.9086821  0.53001352]
 [0.59255229 0.86795953 0.55539561 0.05899527 0.24787112 0.72908632
  0.14002147 0.48980267 0.9611967  0.98500049]
 [0.27454449 0.96964129 0.03111908 0.27971727 0.46443269 0.74694707
  0.8678583 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) `hint: mean`

In [36]:
Random_Array_2=np.random.random(30)
print(Random_Array_2)

print(Random_Array_2.mean())


[0.36820083 0.30783648 0.32670605 0.34109828 0.24463997 0.04614945
 0.85114311 0.68957548 0.42768911 0.43196131 0.24636405 0.97335728
 0.60314308 0.67535767 0.79174202 0.63687267 0.93045412 0.3575312
 0.76097178 0.80113966 0.61502886 0.25156414 0.57388103 0.17909387
 0.50770173 0.23637931 0.52340418 0.32078031 0.41107209 0.92401763]
0.5118285575461295


#### 15. Create a 2d array as following, with 1 on the border and 0 inside.. see generated array (★☆☆)



```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```



In [40]:
Two_d_array = np.ones((10,10))
print(Two_d_array.shape)
Two_d_array[1:-1,1:-1] = 0
print(Two_d_array)

(10, 10)
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★★☆) `hint: see generated array np.pad   `

In [42]:
np.pad?
Two_d_array[:, [0, -1]] = 0
Two_d_array[[0, -1], :] = 0
print(Two_d_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [43]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


 ####18  What is the result of the following expression? (★☆☆) `hint: indexing the nan using np.nan`



```
Z = np.ones((5,5))
Z[0,1]=np.nan
Z
```



In [44]:
Z = np.ones((5,5))
Z[0,1]=np.nan
Z

array([[ 1., nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 18. Now, use this expression to find the index of your nan


```
np.argwhere(x!=x)    Hint: x is your array
```





In [77]:
Z = np.ones((5,5))
Z[0,1]=np.nan
print(Z)
print(np.argwhere(Z=="nan"))

[[ 1. nan  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  after removing the cwd from sys.path.


20. Generate the following array 


```
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```



In [86]:
Array1=[ 1,  2,  3,  4]
Array2=[5,  6,  7,  8]
Array3=[9, 10, 11, 12]
Array4=[13, 14, 15, 16]

Array_1234=np.array([Array1,Array2,Array3,Array4])
print(Array_1234)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### 19. Extract the following values `array([ 1,  6, 11, 16])`. ` Hint: use np.diagonal()`

In [87]:
np.diagonal?
Array_Extract=np.diagonal(Array_1234, axis1=0, axis2=1)
print(Array_Extract)

[ 1  6 11 16]


#### 20. Try to use `np.diag` to Create a 5x5 matrix with diagonal values 11,11,11,11 (★★☆) Hint: use np.diag with k=0 and [11,11,11,11]. -- diag([11,11,11,11],k=-0)

In [52]:
np.diag?
DST_0=np.array([11,11,11,11])
DST_1=np.diag(DST_0,k=1)
print(DST_1)

[[ 0 11  0  0  0]
 [ 0  0 11  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 11]
 [ 0  0  0  0  0]]


#### 21.  Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) `Hint: use k=-1 when calling np.diag`

In [53]:
x = np.diag([1, 2, 3, 4], k=1)
print(x)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


####22. Create a 8x8 matrix and fill it with a given pattern (★☆☆) Hint: use np.zeros and do the replace 



```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [56]:
MO_Array= np.zeros((8,8),dtype=str)
MO_Array[1::2,::2] = "M"
MO_Array[::2,1::2] = "O"
print(MO_Array)

[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 23. Use the `np.tile` to generate the same pattern 

```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [57]:
np.tile?
MO_Array_1= np.tile("O")


#### 24. Generate then Normalize a 5x5 random matrix (★☆☆)  `hint: Normalization_array = (x_arr -mean_value(x))/std_value(x)`

In [58]:
Normalization_array = np.random.random((5,5))
Normalization_array = (Normalization_array - np.mean (Normalization_array)) / (np.std (Normalization_array))
print(Normalization_array)

[[ 1.48857927  0.52758986  1.07216372 -2.04958614 -0.0998971 ]
 [ 0.1423541  -0.15953125 -0.79973061 -1.70056647  0.77309916]
 [ 1.24385836  1.44140193 -0.82294027 -0.135355   -1.58638544]
 [ 1.40075226 -1.29400772 -0.45671292  0.79909076  0.5778717 ]
 [ 0.13910632 -0.18147512 -0.9209921   0.64318127 -0.04186857]]


#### 25. generate any 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

where 

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
```
will return

```
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
```




In [59]:
One_Dimentioal_Array = np.arange(11)
One_Dimentioal_Array[(3 < One_Dimentioal_Array) & (One_Dimentioal_Array < 8)] *= -1
print(One_Dimentioal_Array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. Consider an integer vector Z, comment any iligal expressions (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [61]:
Z=10
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

# Dr.Mohammad. All of these  expressions are correct

10000000000
512
False
10j
10.0
False


#### 27. Generate two randon 1D array, How to find common values between two arrays? (★☆☆) `Hint: use intersect1d(Arr1,Arr2)`

In [65]:
First_ARR = np.array([0, 100, 15, 200, 35, 300])
Second_ARR =np.array([100, 200, 300])
print(np.intersect1d(First_ARR, Second_ARR))


[100 200 300]


#### 28. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
DST= np.seterr(**defaults)

####29. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [66]:
np.sqrt(-1) == np.emath.sqrt(-1)

#I think that this function is False 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False